services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./data:/data/import
    networks:
      - million-network

  million-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: million_api
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data:/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDatabaseSettings__ConnectionString=mongodb://mongo:27017
      - MongoDatabaseSettings__DatabaseName=MillionRealEstate
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - mongo
    networks:
      - million-network

volumes:
  mongo-data:

networks:
  million-network:
    driver: bridge
